name: test666
favicon: null
layout_spectrum: 0.024949972983449697
typography_spectrum: 0.05391189712099731
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9915789095684886
  lightness: 0.15081733372062445
  saturation: 0.24389827391132712
  rhythmicContrast: 0.4951054921839386
purpose: []
